#ifndef MINI_MODBUS_ID_H_
#define MINI_MODBUS_ID_H_


#define TAYFUN_FAMILY			0x100



#define BUMERANG_FAMILY			0x200
#define BUMERANG_PUO			(BUMERANG_FAMILY | 0x01)
#define BUMERANG_PS				(BUMERANG_FAMILY | 0x02)
#define BUMERANG_EBS			(BUMERANG_FAMILY | 0x03)
#define BUMERANG_MTO			(BUMERANG_FAMILY | 0x04)
#define BUMERANG_BVMV			(BUMERANG_FAMILY | 0x05)

#define COMMON_FAMILY			0x1000
#define COMMON_OUTPUTS_16		(COMMON_FAMILY | 0x01)
#define COMMON_INPUTS64			(COMMON_FAMILY | 0x02)
#define COMMON_TERMO			(COMMON_FAMILY | 0x03)
#define COMMON_PROC_MODULE		(COMMON_FAMILY | 0x04)
#define COMMON_DUP				(COMMON_FAMILY | 0x05)


#define SEMZ_FAMILY				0x300
#define SEMZ_CAN				(SEMZ_FAMILY | 0x01)


#endif

